import { addHours, addMinutes, subHours } from "date-fns";
import type { CallRecord, ProspectInput, RequirementInput } from "./types";
import { getDb, getSettings, hydrateProspect, hydrateRequirement } from "./db";

function hoursAgo(h: number) {
  return subHours(new Date(), h).toISOString();
}
function hoursFromNow(h: number) {
  return addHours(new Date(), h).toISOString();
}

export function sampleProspects(): ProspectInput[] {
  return [
    {
      businessName: "ABC Equipment LLC",
      phone: "804-555-1234",
      alternatePhone: "804-555-1290",
      email: "abc@email.com",
      website: "abcequipment.com",
      address: "4100 Witchduck Rd",
      city: "Virginia Beach",
      state: "VA",
      zip: "23455",
      contactName: "John Hale",
      contactTitle: "Owner",
      leadType: "Dealer",
      status: "Callback",
      priority: "Hot",
      source: "Sample",
      remarks: "Interested in tractor parts. Asked to call after 3 PM.",
      nextAction: "Call John after 3 PM.",
      extra: {},
      lastCalledAt: hoursAgo(2),
      nextCallbackAt: addMinutes(new Date(), 45).toISOString(),
      callAttempts: 4,
    },
    {
      businessName: "Smith Tractor",
      phone: "757-555-2211",
      alternatePhone: "",
      email: "sales@smithtractor.com",
      website: "smithtractor.com",
      address: "900 Granby St",
      city: "Norfolk",
      state: "VA",
      zip: "23510",
      contactName: "Dave Smith",
      contactTitle: "Parts Manager",
      leadType: "Dealer",
      status: "Called",
      priority: "Warm",
      source: "Sample",
      remarks: "Left voicemail this morning.",
      nextAction: "Try again this afternoon.",
      extra: {},
      lastCalledAt: hoursAgo(4),
      nextCallbackAt: null,
      callAttempts: 2,
    },
    {
      businessName: "KTR Equipment",
      phone: "804-555-7788",
      alternatePhone: "",
      email: "info@ktrequip.com",
      website: "ktrequip.com",
      address: "2211 Midlothian Tpke",
      city: "Richmond",
      state: "VA",
      zip: "23224",
      contactName: "Karen Reed",
      contactTitle: "Office Manager",
      leadType: "Dealer",
      status: "Callback",
      priority: "Hot",
      source: "Sample",
      remarks: "Spoke with receptionist. Call back requested.",
      nextAction: "Ask for Karen.",
      extra: {},
      lastCalledAt: hoursAgo(6),
      nextCallbackAt: hoursAgo(1),
      callAttempts: 3,
    },
    {
      businessName: "Harbor Forklifts",
      phone: "757-555-8822",
      alternatePhone: "",
      email: "maria@harborfork.com",
      website: "",
      address: "",
      city: "Chesapeake",
      state: "VA",
      zip: "23320",
      contactName: "Maria Chen",
      contactTitle: "Buyer",
      leadType: "End User",
      status: "New",
      priority: "Hot",
      source: "Sample",
      remarks: "",
      nextAction: "First call.",
      extra: {},
      callAttempts: 0,
    },
    {
      businessName: "Valley Ag Supply",
      phone: "540-555-3344",
      alternatePhone: "540-555-3300",
      email: "hello@valleyag.com",
      website: "valleyagsupply.com",
      address: "12 Frontier Dr",
      city: "Staunton",
      state: "VA",
      zip: "24401",
      contactName: "John Harper",
      contactTitle: "Owner",
      leadType: "Dealer",
      status: "To Call",
      priority: "Warm",
      source: "Sample",
      remarks: "Seasonal — busiest in spring.",
      nextAction: "Introduce parts catalog.",
      extra: {},
      callAttempts: 0,
    },
    {
      businessName: "Tidewater Truck Parts",
      phone: "757-555-6677",
      alternatePhone: "",
      email: "parts@twtruck.com",
      website: "",
      address: "",
      city: "Newport News",
      state: "VA",
      zip: "23607",
      contactName: "",
      contactTitle: "",
      leadType: "Distributor",
      status: "Follow-up",
      priority: "Warm",
      source: "Sample",
      remarks: "Send pricing sheet.",
      nextAction: "Email quote then call.",
      extra: {},
      lastCalledAt: hoursAgo(26),
      nextCallbackAt: hoursFromNow(20),
      callAttempts: 1,
    },
    {
      businessName: "Piedmont Implements",
      phone: "434-555-4400",
      alternatePhone: "",
      email: "hello@piedmontimp.com",
      website: "",
      address: "",
      city: "Lynchburg",
      state: "VA",
      zip: "24501",
      contactName: "Ray Collins",
      contactTitle: "GM",
      leadType: "Dealer",
      status: "Interested",
      priority: "Hot",
      source: "Sample",
      remarks: "Wants bulk hose pricing.",
      nextAction: "Send quote.",
      extra: {},
      lastCalledAt: hoursAgo(30),
      nextCallbackAt: hoursFromNow(4),
      callAttempts: 2,
    },
    {
      businessName: "Bay Diesel Works",
      phone: "757-555-0199",
      alternatePhone: "",
      email: "parts@baydiesel.com",
      website: "baydiesel.com",
      address: "",
      city: "Hampton",
      state: "VA",
      zip: "23661",
      contactName: "Al Perez",
      contactTitle: "Service Manager",
      leadType: "Shop",
      status: "New",
      priority: "Cold",
      source: "Sample",
      remarks: "",
      nextAction: "",
      extra: {},
      callAttempts: 0,
    },
    {
      businessName: "Blue Ridge Hydraulics",
      phone: "540-555-9012",
      alternatePhone: "",
      email: "info@brhydro.com",
      website: "",
      address: "",
      city: "Roanoke",
      state: "VA",
      zip: "24016",
      contactName: "Nina Walsh",
      contactTitle: "Purchasing",
      leadType: "Distributor",
      status: "Qualified",
      priority: "Hot",
      source: "Sample",
      remarks: "Ready for a trial order.",
      nextAction: "Confirm SKUs.",
      extra: {},
      lastCalledAt: hoursAgo(50),
      nextCallbackAt: hoursFromNow(28),
      callAttempts: 5,
    },
    {
      businessName: "Capitol Fleet Service",
      phone: "703-555-6161",
      alternatePhone: "",
      email: "fleet@capfleet.com",
      website: "",
      address: "",
      city: "Alexandria",
      state: "VA",
      zip: "22314",
      contactName: "Tom Nguyen",
      contactTitle: "Fleet Supervisor",
      leadType: "End User",
      status: "Won",
      priority: "Warm",
      source: "Sample",
      remarks: "First PO received.",
      nextAction: "Onboard.",
      extra: {},
      lastCalledAt: hoursAgo(80),
      nextCallbackAt: null,
      callAttempts: 6,
    },
    {
      businessName: "Shenandoah Outdoor Power",
      phone: "540-555-2727",
      alternatePhone: "",
      email: "",
      website: "",
      address: "",
      city: "Harrisonburg",
      state: "VA",
      zip: "22801",
      contactName: "",
      contactTitle: "",
      leadType: "Dealer",
      status: "Lost",
      priority: "Cold",
      source: "Sample",
      remarks: "Already has a supplier.",
      nextAction: "",
      extra: {},
      lastCalledAt: hoursAgo(200),
      nextCallbackAt: null,
      callAttempts: 3,
    },
    {
      businessName: "Potomac Marine Supply",
      phone: "703-555-4488",
      alternatePhone: "",
      email: "dock@potomacmarine.com",
      website: "",
      address: "",
      city: "Woodbridge",
      state: "VA",
      zip: "22191",
      contactName: "Lisa Grant",
      contactTitle: "Owner",
      leadType: "Marine",
      status: "Do Not Call",
      priority: "Cold",
      source: "Sample",
      remarks: "Asked to be removed.",
      nextAction: "",
      extra: {},
      lastCalledAt: hoursAgo(12),
      nextCallbackAt: null,
      callAttempts: 1,
    },
  ];
}

export async function loadSampleWorkspace(): Promise<number> {
  const db = getDb();
  const settings = await getSettings();
  const rows = sampleProspects().map((r) => hydrateProspect(r, settings));
  await db.prospects.bulkAdd(rows);
  const byName = new Map(rows.map((p) => [p.businessName, p]));
  const now = Date.now();
  const calls: CallRecord[] = [
    {
      id: crypto.randomUUID(),
      prospectId: byName.get("ABC Equipment LLC")?.id ?? rows[0].id,
      calledAt: new Date(now - 2 * 3600000).toISOString(),
      outcome: "Interested",
      contactName: "John Hale",
      notes: "Spoke with John. Asked for pricing on tractor parts.",
      callbackAt: byName.get("ABC Equipment LLC")?.nextCallbackAt ?? null,
      nextAction: "Call John after 3 PM.",
      createdAt: new Date(now - 2 * 3600000).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      prospectId: byName.get("Smith Tractor")?.id ?? rows[1].id,
      calledAt: new Date(now - 4 * 3600000).toISOString(),
      outcome: "No Answer",
      contactName: "Dave Smith",
      notes: "Try again later.",
      callbackAt: null,
      nextAction: "Try again this afternoon.",
      createdAt: new Date(now - 4 * 3600000).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      prospectId: byName.get("KTR Equipment")?.id ?? rows[2].id,
      calledAt: new Date(now - 6 * 3600000).toISOString(),
      outcome: "Callback Requested",
      contactName: "Reception",
      notes: "Receptionist asked to call back.",
      callbackAt: byName.get("KTR Equipment")?.nextCallbackAt ?? null,
      nextAction: "Ask for Karen.",
      createdAt: new Date(now - 6 * 3600000).toISOString(),
    },
  ];
  await db.calls.bulkAdd(calls);

  const reqs: RequirementInput[] = [
    {
      prospectId: byName.get("ABC Equipment LLC")?.id ?? rows[0].id,
      partNumber: "RE507541",
      condition: "OEM",
      brand: "John Deere",
      model: "5075E",
      priceQuoted: "48.50",
      quantity: "2",
      notes: "Hydraulic filter. Needs this week.",
      status: "Open",
    },
    {
      prospectId: byName.get("Smith Tractor")?.id ?? rows[1].id,
      partNumber: "T0110-37500",
      condition: "Used",
      brand: "Kubota",
      model: "L3901",
      priceQuoted: "220.00",
      quantity: "1",
      notes: "Clutch assembly. Confirm takeoff condition.",
      status: "Quoted",
    },
    {
      prospectId: byName.get("KTR Equipment")?.id ?? rows[2].id,
      partNumber: "3715863M1",
      condition: "Aftermarket",
      brand: "Massey Ferguson",
      model: "4710",
      priceQuoted: "89.00",
      quantity: "4",
      notes: "Fuel filters. Call after 3 PM.",
      status: "Open",
    },
    {
      prospectId: byName.get("Piedmont Implements")?.id ?? rows[5].id,
      partNumber: "R35181",
      condition: "Aftermarket",
      brand: "Case IH",
      model: "Maxxum 110",
      priceQuoted: "32.90",
      quantity: "6",
      notes: "Brake pads. Bulk hose pricing also requested.",
      status: "Open",
    },
    {
      prospectId: byName.get("Blue Ridge Hydraulics")?.id ?? rows[7].id,
      partNumber: "STB/0307-923",
      condition: "OEM",
      brand: "CAT",
      model: "D3K2",
      priceQuoted: "27.14",
      quantity: "10",
      notes: "Open ball bearing. Trial order.",
      status: "Quoted",
    },
  ];
  await db.requirements.bulkAdd(reqs.map((r) => hydrateRequirement(r)));
  return rows.length;
}
