/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbacksRouteImport } from './routes/callbacks'
import { Route as ExportRouteImport } from './routes/export'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbacksRoute = CallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProspectsRoute,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callbacks': typeof CallbacksRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/queue': typeof QueueRoute
  '/requirements': typeof RequirementsRoute
  '/settings': typeof SettingsRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callbacks': typeof CallbacksRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/queue': typeof QueueRoute
  '/requirements': typeof RequirementsRoute
  '/settings': typeof SettingsRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects': typeof ProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callbacks': typeof CallbacksRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/queue': typeof QueueRoute
  '/requirements': typeof RequirementsRoute
  '/settings': typeof SettingsRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callbacks'
    | '/export'
    | '/history'
    | '/import'
    | '/prospects'
    | '/queue'
    | '/requirements'
    | '/settings'
    | '/prospects/$id'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callbacks'
    | '/export'
    | '/history'
    | '/import'
    | '/queue'
    | '/requirements'
    | '/settings'
    | '/prospects/$id'
    | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/callbacks'
    | '/export'
    | '/history'
    | '/import'
    | '/prospects'
    | '/queue'
    | '/requirements'
    | '/settings'
    | '/prospects/$id'
    | '/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbacksRoute: typeof CallbacksRoute
  ExportRoute: typeof ExportRoute
  HistoryRoute: typeof HistoryRoute
  ImportRoute: typeof ImportRoute
  ProspectsRoute: typeof ProspectsRouteWithChildren
  QueueRoute: typeof QueueRoute
  RequirementsRoute: typeof RequirementsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbacks': {
      id: '/callbacks'
      path: '/callbacks'
      fullPath: '/callbacks'
      preLoaderRoute: typeof CallbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof ProspectsRoute
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof ProspectsRoute
    }
  }
}

interface ProspectsRouteChildren {
  ProspectsIdRoute: typeof ProspectsIdRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
}

const ProspectsRouteChildren: ProspectsRouteChildren = {
  ProspectsIdRoute: ProspectsIdRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
}

const ProspectsRouteWithChildren = ProspectsRoute._addFileChildren(
  ProspectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbacksRoute: CallbacksRoute,
  ExportRoute: ExportRoute,
  HistoryRoute: HistoryRoute,
  ImportRoute: ImportRoute,
  ProspectsRoute: ProspectsRouteWithChildren,
  QueueRoute: QueueRoute,
  RequirementsRoute: RequirementsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
